// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Devsu.Core.Entities;

public partial class Cuenta
{
    public int IdCuenta { get; set; }

    public int IdCliente { get; set; }

    public string Numero { get; set; }

    public string Tipo { get; set; }

    public decimal SaldoInicial { get; set; }

    public bool Estado { get; set; }

    public bool Eliminado { get; set; }

    public virtual Cliente IdClienteNavigation { get; set; }

    public virtual ICollection<Movimiento> Movimiento { get; set; } = new List<Movimiento>();
}