// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Devsu.Core.Entities;

public partial class Movimiento
{
    public int IdMovimiento { get; set; }

    public int IdCuenta { get; set; }

    public DateTime Fecha { get; set; }

    public string Tipo { get; set; }

    public decimal Valor { get; set; }

    public decimal Saldo { get; set; }

    public decimal Limite { get; set; }

    public bool Eliminado { get; set; }

    public virtual Cuenta IdCuentaNavigation { get; set; }
}